### ISSUE TITLE
Is there any English document of the otama?

### ISSUE THREAD

**Issue by willard-yuan** [nagadomi/otama#1]
Hi, nagadomi

I'm very interested in CBIR and your **otama** project is very great. I try to run the otama following the Japanese document, but the language really makes me hard to understand the document since I'm not a Japanese. Is there any English document to read?

**Comment by nagadomi** [comment]
There is no English documentation of otama.
and also otama does not have enough documentation in Japanese.
Probably [Ruby test script](https://github.com/nagadomi/otama/blob/master/ruby/test.rb) and [example code](https://github.com/nagadomi/otama/tree/master/examples) helps to understand how to use otama.

I will translate [Installation](https://github.com/nagadomi/otama/wiki/Building%20from%20source) and [Ruby API](https://github.com/nagadomi/otama/wiki/Ruby-API) section.
Please wait few days.

**Comment by willard-yuan** [comment]
Thanks. It's a great work~
